AllCops:
  Exclude:
    - '.bundle/**/*'
    - 'vendor/**/*'
    # We shouldn't need the above but for now there's a bug in rubocop
    - 'lib/admin/dropsonde_protocol/*'
    - 'spec/support/ccdb/*'
    - 'spec/support/uaadb/*'

AbcSize:
  Enabled: false

AlignHash:
  EnforcedHashRocketStyle: table

BlockNesting:
  Enabled: false

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Encoding:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

IndentArray:
  EnforcedStyle: align_brackets
  
IndentHash:
  EnforcedStyle: align_braces
  
LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ParameterLists:
  Enabled: false

PerceivedComplexity:
  Enabled: false
